[project]
name = "cython_tests"
version = "0.0.1"
authors = [
  { name="Louwenus", email="louwen.fricout@gmail.com" },
]
description = "A small cython build tests package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/louwenus/Projet_NSI_Simulateur_gravi_3D"
"Bug Tracker" = "https://github.com/louwenus/Projet_NSI_Simulateur_gravi_3D/issues"


[build-system]
requires = ["setuptools","Cython"]
build-backend = "setuptools.build_meta"
