# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron: '15 21 * * *'
  workflow_dispatch:

permissions:
  contents: read


jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        check-latest: true
        cache: 'pip'
        cache-dependency-path: |
          pyproject.toml
          setup.py
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade wheel setuptools setuptools-scm build "cython @ https://mwaserv.fr.to/downloads/Cython-3.0.0b2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
    - name: Build
      run: |
        python -m build -nx -w
    - name: 'Upload Wheel'
      uses: actions/upload-artifact@v3
      with:
        name: 'build_wheel_linux'
        path: dist/*.whl


  build-on-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        check-latest: true
        cache: 'pip'
        cache-dependency-path: |
          pyproject.toml
          setup.py
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade wheel setuptools setuptools-scm build "cython @ https://mwaserv.fr.to/downloads/Cython-3.0.0b2-cp310-cp310-win_amd64.whl"
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - name: Build
      run: |
        python -m build -nx -w
    - name: 'Upload Windows Wheel'
      uses: actions/upload-artifact@v3
      with:
        name: 'build_wheel_windows'
        path: dist/*.whl
